### ISSUE TITLE
Cucumber-chef test hangs

### ISSUE THREAD

**Issue by sameersegal** [Atalanta/cucumber-chef#86] opened 2012-10-04 13:55 UTC
Hi, I have written this feature (I am new to Cucumber & Chef) :

```
 Background:
    * I have a server called "appserver"
    * "appserver" is running "ubuntu" "lucid"
    * "appserver" has been provisioned
    * the "appserver-role" role has been added to the "appserver" run list
    * the chef-client has been run on "appserver"
    * I ssh to "appserver" with the following credentials:
      | username | keyfile |
      | root | ../.ssh/id_rsa |

  Scenario: Check Play has been downloaded from S3
    When I run "ls /root/Code/play.zip"
       Then I should not see "No such file or directory" in the output

  Scenario: Check Play unpacked
    When I run "which play"
       Then I should see "/usr/bin/play" in the output
```

And it always seems to fail the 2nd time if I have `* the chef-client has been run on "appserver"` but if I remove it, then it always fails when I run it on a new test lab

```
  Background:                                                              # ./appserver/appserver.feature:7
  >>> servers are being preserved
    * I have a server called "appserver"                                   # cucumber-chef-2.0.4/lib/cucumber/chef/steps/provision_steps.rb:22
    * "appserver" is running "ubuntu" "lucid"                              # cucumber-chef-2.0.4/lib/cucumber/chef/steps/provision_steps.rb:26
    * "appserver" has been provisioned                                     # cucumber-chef-2.0.4/lib/cucumber/chef/steps/provision_steps.rb:46
    * the "appserver-role" role has been added to the "appserver" run list # cucumber-chef-2.0.4/lib/cucumber/chef/steps/provision_steps.rb:50
  >>> chef-client ran on node 'appserver'
    * the chef-client has been run on "appserver"                          # cucumber-chef-2.0.4/lib/cucumber/chef/steps/provision_steps.rb:62
    * I ssh to "appserver" with the following credentials:                 # cucumber-chef-2.0.4/lib/cucumber/chef/steps/ssh_steps.rb:57
      | username | keyfile        |
      | root     | ../.ssh/id_rsa |

  Scenario: Check Play has been downloaded from S3                         # ./appserver/appserver.feature:17
    When I run "ls /root/Code/play.zip"                                    # cucumber-chef-2.0.4/lib/cucumber/chef/steps/ssh_steps.rb:77
    Then I should not see "No such file or directory" in the output        # cucumber-chef-2.0.4/lib/cucumber/chef/steps/ssh_steps.rb:81

  Scenario: Check Play unpacked                                            # ./appserver/appserver.feature:21
  >>> servers are being preserved
    * the chef-client has been run on "appserver"                          # cucumber-chef-2.0.4/lib/cucumber/chef/steps/provision_steps.rb:62
      command_run_remote(/usr/bin/chef-client -j /etc/chef/attributes.json -N appserver ) failed (256) (RuntimeError)
      ./appserver/appserver.feature:12:in `* the chef-client has been run on "appserver"'
    When I run "which play"                                                # cucumber-chef-2.0.4/lib/cucumber/chef/steps/ssh_steps.rb:77
    Then I should see "/usr/bin/play" in the output                        # cucumber-chef-2.0.4/lib/cucumber/chef/steps/ssh_steps.rb:81
      exit (SystemExit)
      /home/ubuntu/features/support/env.rb:50:in `exit'
      /home/ubuntu/features/support/env.rb:50:in `After'

Failing Scenarios:
cucumber ./appserver/appserver.feature:21 # Scenario: Check Play unpacked

2 scenarios (1 failed, 1 passed)
16 steps (1 failed, 3 skipped, 12 passed)
3m4.085s
```

What am I doing wrong? Also is there a better place to post such questions?

**Comment by zpatten** [comment] 2012-10-11 20:31
Hey; sorry I've been very busy with many personal things over the past few weeks.  I will have the time this weekend to resolve this issue and get the fix in place.

Nothing your doing wrong I would say; seems I forgot to update the path to the test-lab ssh-key in the example test during my last major update.

**Comment by zpatten** [comment] 2012-10-28 20:56
Sorry for the delay; this should be fixed in the latest release.

**Comment by gburch** [comment] 2012-12-13 01:41
I am having the same problem and I am running off master. Is there any more details to help me diagnose? cucumber-chef ssh test works but when doing:
- I ssh to "test" with the following credentials:
    | username | keyfile |
    | root | ./.cucumber-chef/id_rsa-ubuntu |

It fails with:
command_run_remote(/usr/bin/chef-client -j /etc/chef/attributes.json -N test ) failed (256) (RuntimeError)

**Comment by gburch** [comment] 2012-12-13 01:45
Actually I solved it now. It was failing late so it was a red herring. I did not have the chef-client cookbook in my repository. This may also be the issue the person above was having.

**Comment by zpatten** [comment] 2012-12-13 20:04
Indeed; the code needs to surface these errors a little better I think.  Your best bet until that happens is to use the cucumber-chef ssh command, or diagnose command to view the chef-client logs on the LX container.

**Comment by zpatten** [comment] 2013-01-16 18:58
Just wanted to note; if your having issues you can also run:
`cucmber-chef diagnose [container]`
This will give you the `chef-stacktrace.out` and tail the last bit of the `client.log`.  The stack trace generally has enough information in these cases to make obvious what the issue is.

**Comment by zpatten** [comment] 2013-01-25 21:40
The latest RC versions have much better logging/capture of SSH and Shell sessions.

**Closed as completed by zpatten** 2013-01-25 21:40 UTC
Labels: bug
