### ISSUE TITLE
Test Lab Bootstraps Hang - Waiting on validation.pem and webui.pem to appear

### ISSUE THREAD

**Issue by bgkittrell** [Atalanta/cucumber-chef#108] opened 2013-03-14 04:00 UTC
I just started setting up my environment, but when I run cucumber-chef setup it times out on the boostrap process.  Looking at the log I see "Waiting on validation.pem and webui.pem to appear".

What are those files, and where should they be?

**Comment by zpatten** [comment] 2013-03-20 01:04
The message indicates that the test lab is waiting on the chef server to generate it's `validation.pem` and `webui.pem` keys.

Tail your cucumber-chef log file located in `<chef-repo>/.cucumber-chef/cucumber-chef.log` during setup.  The issue should be apparent in the log.

On rare occasion, I've seen a test lab hang in this spot before, something way down in the chef seems to fail as far as I could tell.

I wouldn't stress this too much; you can easily destroy and re-create the test lab.  If the issue is persistent then we have a problem.

**Comment by zpatten** [comment] 2013-03-29 23:37
Ok; so there is something going seriously wrong.  I haven't been able to nail down root cause 100%; but the chef-server installation via the Opscode apt-repo is no longer working.

I was planning on removing this at some point and replacing it with a bootstrap process that will work for Chef versions 0.10.x & 0.11.x. (Since Opscode didn't release 0.11.x via an apt-repo, I got the impression they would be dropping it anyways).

I'll get the bootstrap fixed this weekend and a new version pushed out.  If I can pull it off I will be releasing a non-rc 3.0 version before the weekend is over.

**Comment by zpatten** [comment] 2013-03-31 20:32
Making progress

**Comment by zpatten** [comment] 2013-04-02 04:32
I've got everything switched over to chef-solo for the bootstrap now; working out a kink in rc.2, a somewhat known issue with chef; at least I have hit it before.  I'll update once I have this resolved.

**Comment by zpatten** [comment] 2013-04-06 23:01
This should be resolved in the latest RC versions (i.e. 3.0.0.rc.5 and up); feel free to reopen this if the issue is not resolved for you.

**Closed as completed by zpatten** 2013-04-06 23:01 UTC
Labels: bug
