### ISSUE TITLE
Cucumber-chef setup hangs

### ISSUE THREAD

**Issue by metalsok** [Atalanta/cucumber-chef#128] opened 2013-07-09 08:11 UTC
using cc-chef-repo with c1.medium machine so i guess it is not a memory issue..
Any help is appreciated!

Starting Chef Client, version 11.4.4
Compiling Cookbooks...
# 
# Recipe Compile Error in /tmp/chef-solo/cookbooks/chef-server/recipes/default.rb
## RuntimeError

Could not locate chef-server package matching version 'latest' for node.
## Cookbook Trace:

  /tmp/chef-solo/cookbooks/chef-server/recipes/default.rb:29:in `from_file'
## Relevant File Content:

/tmp/chef-solo/cookbooks/chef-server/recipes/default.rb:

 22:                                                          node['chef-server']['prereleases'],
 23:                                                          node['chef-server']['nightlies'])
 24:    unless omnibus_package
 25:      err_msg = "Could not locate chef-server"
 26:      err_msg << " pre-release" if node['chef-server']['prereleases']
 27:      err_msg << " nightly" if node['chef-server']['nightlies']
 28:      err_msg << " package matching version '#{node['chef-server']['version']}' for node."
 29>>     raise err_msg
 30:    end
 31:  else
 32:    omnibus_package = node['chef-server']['package_file']
 33:  end
 34:  
 35:  package_name = ::File.basename(omnibus_package)
 36:  package_local_path = "#{Chef::Config[:file_cache_path]}/#{package_name}"
 37:  
 38:  # omnibus_package is remote (ie a URI) let's download it

Chef Client failed. 0 resources updated
- cat
- tee /etc/chef-server/chef-server.rb
  tee: /etc/chef-server/chef-server.rb: No such file or directory
  #
  # Auto-generated by Cucumber-Chef v#{Cucumber::Chef::VERSION} -- DO NOT EDIT!
  #
  server_name = "54.229.88.167"
  #
  topology                "standalone"
  api_fqdn                server_name
  nginx['url']          = "https://#{server_name}"
  nginx['server_name']  = server_name
  lb['fqdn']            = server_name
  bookshelf['vip']      = server_name
- sudo chef-server-ctl reconfigure
  sudo: chef-server-ctl: command not found
- echo -n 'Waiting on chef-validator.pem and chef-webui.pem to appear...'
  Waiting on chef-validator.pem and chef-webui.pem to appear...+ '[' -f /etc/chef-server/chef-validator.pem ']'
- echo -n .
  .+ sleep 1
- '[' -f /etc/chef-server/chef-validator.pem ']'
- echo -n .
  .+ sleep 1
- '[' -f /etc/chef-server/chef-validator.pem ']'
- echo -n .
  .+ sleep 1
- '[' -f /etc/chef-server/chef-validator.pem ']'
- echo -n .
  .+ sleep 1

**Comment by zpatten** [comment] 2013-07-10 22:47
I've seen this a few times before; I'll try to dig up the cause for you.

**Comment by metalsok** [comment] 2013-07-11 07:43
Thank you for your reply , managed to solve that one by changing the :version => "latest" to :version => "10.24.0". in the cucumber-chef config.rb so the chef_pre_11 changed from false to true. noob mistake i guess!

**Comment by zpatten** [comment] 2013-07-15 21:41
No worries; I'm gonna close this out; feel free to reopen it if you are still having issues.

**Closed as completed by zpatten** 2013-07-15 21:41 UTC
